<?php

namespace AppBundle\Repository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends \Doctrine\ORM\EntityRepository
{
	public function showTaxref($q, $page)
	{
		// SELECT * from taxref where (nom_ref LIKE 'acr%' OR nom_vern LIKE 'acr%');
		  $query = $this->_em->createQuery(
            'SELECT t.id, t.nomVern, t.nomRef FROM AppBundle:Taxref t
            WHERE t.nomRef LIKE :q OR t.nomVern LIKE :q'
            )->setParameter('q', '%'.$q.'%');

		   $results = $query->setMaxResults($page)->getResult();
		  
		   return $results;
	}
}
