<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsers(){
        return $this->createQueryBuilder('a')
            ->select('a.id',
                    'a.pseudo',
                    'a.account',
                    'a.username',
                    'a.member',
                    'a.validMail',
                    'a.dateRegistration',
                    'IDENTITY(a.justificatif) as justificatif')
            ->where('a.account != :x')
            ->setParameter('x', 'Administrateur')
            ->getQuery()
            ->getResult();
    }

    public function getParticulierNb(){
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->where('a.account = :x')
            ->setParameter('x', 'Particulier' )
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getNaturalisteNb(){
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->where('a.account = :x')
            ->setParameter('x', 'Naturaliste' )
            ->getQuery()
            ->getSingleScalarResult();
    }






}
